services:
  app:
    build: .
    container_name: next_app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: >
      sh -c "sleep 5 &&
             npx prisma db push &&
             npx prisma db seed &&
             npm run start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
